function output = cpm_grid_template(freeparams,fixedparams,data)
% CPM_GRID_TEMPLATE This is where the cognitive (or other) model would be defined
%
%   This function is called for every point in the parameter meshgrid, the
%   varying parameters are bundled into the freeparams structure, non
%   varying parameters are bundled into the fixedparams structure.
%   Experiment and stimuli data are in the data structure.
%
%   INPUTS:
%       freeparams: a structure representing a point in the parameter meshgrid
%                   freeparams.Theta_1 == SOME_VALUE
%                   freeparams.Theta_2 == SOME_VALUE
%                               etc
%
%       fixedparams: a structure representing hyperparameters outside of the
%                    meshgrid
%                    fixedparams.somehyperparameter == SOME_VALUE 
%
%
%       data: a structure contaning experiment data
%             data.ons: stimulus onsets
%             data.dur: stimulus durations
%             data.dt: time resolutions
%             data.some_data: you may preprocess and use your data in any
%                             format by passing it through this structure
%
%   
%   OUTPUTS:
%       output: the neuronal signal generated by the model for the set of
%               parameters and stumuli data given.
%               NOTE: this output vector should have the same length as
%               data.ons
%





    


output = [];

end

